In [5]:
# !python3 -m pip install requests beautifulsoup4 pandas

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

In [7]:
url = "https://www.scrapethissite.com/pages/simple/"
url

'https://www.scrapethissite.com/pages/simple/'

In [8]:
response= requests.get(url, timeout=30)
response

In [9]:
html = response.text
print(html)

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name="robots" content="noindex">
<link href="https://lipis.github.io/flag-icon-css/css/flag-icon.css" rel="stylesheet">


  </head>

  <body>
    <nav id="site-nav">
            <div class="container">
                <div class="col-md-12">
                    <ul class="nav nav-tabs">
                        <li id="nav-homepage">
                            <a href="/" class="nav-link hidden-sm hidden-xs">
                                <img src="/static/images/scraper-icon.png" id="nav-logo">
                                Scrape This Site
                            </a>
                        </li>
                        <li id="nav-sandbox">
                            <a href="/pages/" class="nav-link">
                                <i class="glyphicon glyphicon-console hidden-sm hidden-xs"></i>
                                Sandbox
                            </a>
                        </li>
                        <li id="nav-lessons">
                            <a href="/lessons/" class="nav-link">
                                <i class="glyphicon glyphicon-education hidden-sm hidden-xs"></i>
                                Lessons
                            </a>
                        </li>
                        <li id="nav-faq">
                            <a href="/faq/" class="nav-link">
                                <i class="glyphicon glyphicon-flag hidden-sm hidden-xs"></i>
                                FAQ
                            </a>
                        </li>

                        <li id="nav-login" class="pull-right">
                            <a href="/login/" class="nav-link">
                                Login
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>

        <script type="text/javascript">
            var path = document.location.pathname;
            var tab = undefined;
            if (path === "/"){
                tab = document.querySelector("#nav-homepage");
            } else if (path.indexOf("/faq/") === 0){
                tab = document.querySelector("#nav-faq");
            } else if (path.indexOf("/lessons/") === 0){
                tab = document.querySelector("#nav-lessons");
            } else if (path.indexOf("/pages/") === 0) {
                tab = document.querySelector("#nav-sandbox");
            } else if (path.indexOf("/login/") === 0) {
                tab = document.querySelector("#nav-login");
            }
            tab.classList.add("active")
        </script>



    <div id="page">

        <section id="countries">
            <div class="container">

                <div class="row">
                    <div class="col-md-12">
                        <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
                        </h1>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country&#39;s name.
                        </p>
                        <hr />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <p>
                            <i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
                        <hr />
                    </div>
                    <div class="col-md-6 text-right">
                        <p>

                                Data via
                                <a href="http://peric.github.io/GetCountries/" class="data-attribution" target="_blank">http://peric.github.io/GetCountries/</a>

                        </p>
                        <hr />
                    </div>
                </div>

                <div class="row">

                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br>
                            <strong>Population:</strong> <span class="country-population">84000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br>
                            <strong>Population:</strong> <span class="country-population">4975593</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Kabul</span><br>
                            <strong>Population:</strong> <span class="country-population">29121286</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">St. John&#39;s</span><br>
                            <strong>Population:</strong> <span class="country-population">86754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">The Valley</span><br>
                            <strong>Population:</strong> <span class="country-population">13254</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Tirana</span><br>
                            <strong>Population:</strong> <span class="country-population">2986952</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br>
                            <strong>Population:</strong> <span class="country-population">2968000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Luanda</span><br>
                            <strong>Population:</strong> <span class="country-population">13068161</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">None</span><br>
                            <strong>Population:</strong> <span class="country-population">0</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br>
                            <strong>Population:</strong> <span class="country-population">41343201</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br>
                            <strong>Population:</strong> <span class="country-population">57881</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Vienna</span><br>
                            <strong>Population:</strong> <span class="country-population">8205000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Canberra</span><br>
                            <strong>Population:</strong> <span class="country-population">21515754</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br>
                            <strong>Population:</strong> <span class="country-population">71566</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br>
                            <strong>Population:</strong> <span class="country-population">26711</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Baku</span><br>
                            <strong>Population:</strong> <span class="country-population">8303512</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br>
                            <strong>Population:</strong> <span class="country-population">4590000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br>
                            <strong>Population:</strong> <span class="country-population">285653</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br>
                        </div>
                    </div><!--.col-->

                </div><!--.row-->
                <div class="row">



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br>
                            <strong>Population:</strong> <span class="country-population">156118464</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Brussels</span><br>
                            <strong>Population:</strong> <span class="country-population">10403000</span><br>
                            <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br>
                        </div>
                    </div><!--.col-->



                    <div class="col-md-4 country">
                        <h3 class="country-name">
                            <i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
                        <div class="country-info">
                            <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br>

In [10]:
soup= BeautifulSoup(html,"html.parser")
type(soup)

bs4.BeautifulSoup

In [14]:
heading= soup.find_all("h1")
heading

[<h1>
                             Countries of the World: A Simple Example
                             <small>250 items</small>
 </h1>]

In [15]:
heading_new = soup.find ("h1")
heading_new

<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>

In [18]:
heading_new.get_text

<bound method PageElement.get_text of <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>>

In [19]:
heading_new.get_text

<bound method PageElement.get_text of <h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>>

In [20]:
heading_new.get_text(strip=True)

'Countries of the World: A Simple Example250 items'

In [21]:
first_country = soup.select_one(".country")
first_country

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [22]:
all_countries = soup.select(".country")

In [23]:
all_countries

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [24]:
country_name = first_country.select_one(".country-name")
country_name

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [25]:
capital = first_country.select_one(".country-capital").get_text(strip=True)
capital

'Andorra la Vella'

In [26]:
population = first_country.select_one(".country-population").get_text(strip=True)
population

'84000'

In [27]:
area = first_country.select_one(".country-area").get_text(strip=True)
area

'468.0'

In [28]:
country_url = url
country_url

'https://www.scrapethissite.com/pages/simple/'

In [29]:
country_name = first_country.select_one(".country-name")
country_name

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>

In [30]:
capital = first_country.select_one(".country-capital")
capital

In [31]:
population = first_country.select_one(".country-population")
population

In [32]:
first_coutry_data = {
    "capital": capital,
    "population": population,
    "area": area,
    "url": url
}

first_coutry_data

{'capital': <span class="country-capital">Andorra la Vella</span>,
 'population': <span class="country-population">84000</span>,
 'area': '468.0',
 'url': 'https://www.scrapethissite.com/pages/simple/'}

In [33]:
countries = soup.select(".country")
len(countries)

250

In [34]:
for country in countries:
    name = country.select_one(".country-name").get_text(strip=True)
    print(name)

Andorra
United Arab Emirates
Afghanistan
Antigua and Barbuda
Anguilla
Albania
Armenia
Angola
Antarctica
Argentina
American Samoa
Austria
Australia
Aruba
Åland
Azerbaijan
Bosnia and Herzegovina
Barbados
Bangladesh
Belgium
Burkina Faso
Bulgaria
Bahrain
Burundi
Benin
Saint Barthélemy
Bermuda
Brunei
Bolivia
Bonaire
Brazil
Bahamas
Bhutan
Bouvet Island
Botswana
Belarus
Belize
Canada
Cocos [Keeling] Islands
Democratic Republic of the Congo
Central African Republic
Republic of the Congo
Switzerland
Ivory Coast
Cook Islands
Chile
Cameroon
China
Colombia
Costa Rica
Cuba
Cape Verde
Curacao
Christmas Island
Cyprus
Czech Republic
Germany
Djibouti
Denmark
Dominica
Dominican Republic
Algeria
Ecuador
Estonia
Egypt
Western Sahara
Eritrea
Spain
Ethiopia
Finland
Fiji
Falkland Islands
Micronesia
Faroe Islands
France
Gabon
United Kingdom
Grenada
Georgia
French Guiana
Guernsey
Ghana
Gibraltar
Greenland
Gambia
Guinea
Guadeloupe
Equatorial Guinea
Greece
South Georgia and the South Sandwich Islands
Guatemala
Guam
Guinea-Bissau
Guyana
Hong Kong
Heard Island and McDonald Islands
Honduras
Croatia
Haiti
Hungary
Indonesia
Ireland
Israel
Isle of Man
India
British Indian Ocean Territory
Iraq
Iran
Iceland
Italy
Jersey
Jamaica
Jordan
Japan
Kenya
Kyrgyzstan
Cambodia
Kiribati
Comoros
Saint Kitts and Nevis
North Korea
South Korea
Kuwait
Cayman Islands
Kazakhstan
Laos
Lebanon
Saint Lucia
Liechtenstein
Sri Lanka
Liberia
Lesotho
Lithuania
Luxembourg
Latvia
Libya
Morocco
Monaco
Moldova
Montenegro
Saint Martin
Madagascar
Marshall Islands
Macedonia
Mali
Myanmar [Burma]
Mongolia
Macao
Northern Mariana Islands
Martinique
Mauritania
Montserrat
Malta
Mauritius
Maldives
Malawi
Mexico
Malaysia
Mozambique
Namibia
New Caledonia
Niger
Norfolk Island
Nigeria
Nicaragua
Netherlands
Norway
Nepal
Nauru
Niue
New Zealand
Oman
Panama
Peru
French Polynesia
Papua New Guinea
Philippines
Pakistan
Poland
Saint Pierre and Miquelon
Pitcairn Islands
Puerto Rico
Palestine
Portugal
Palau
Paraguay
Qatar
Réunion
Romania
Serbia
Russia
Rwanda
Saudi Arabia
Solomon Islands
Seychelles
Sudan
Sweden
Singapore
Saint Helena
Slovenia
Svalbard and Jan Mayen
Slovakia
Sierra Leone
San Marino
Senegal
Somalia
Suriname
South Sudan
São Tomé and Príncipe
El Salvador
Sint Maarten
Syria
Swaziland
Turks and Caicos Islands
Chad
French Southern Territories
Togo
Thailand
Tajikistan
Tokelau
East Timor
Turkmenistan
Tunisia
Tonga
Turkey
Trinidad and Tobago
Tuvalu
Taiwan
Tanzania
Ukraine
Uganda
U.S. Minor Outlying Islands
United States
Uruguay
Uzbekistan
Vatican City
Saint Vincent and the Grenadines
Venezuela
British Virgin Islands
U.S. Virgin Islands
Vietnam
Vanuatu
Wallis and Futuna
Samoa
Kosovo
Yemen
Mayotte
South Africa
Zambia
Zimbabwe

In [35]:
# Create an empty list.
# We'll store one dictionary per country in this list.
rows = []
# On the first iteration, 'country' is the first country.
# On the second iteration, it's the second country, and so on.
for country in countries:

    # Find the country name.
    country_name = country.select_one(".country-name")

    # Add one dictionary to our list.
    # Each dictionary becomes one row in our final dataframe.
    rows.append({

        # The name of the country.
        "country_name": country_name.get_text(strip=True),

        # Find the capital city and remove extra spaces.
        "capital": country.select_one(
            ".country-capital"
        ).get_text(strip=True),

        # Find the population and remove extra spaces.
        "population": country.select_one(
            ".country-population"
        ).get_text(strip=True),

        # Find the country's area and remove extra spaces.
        "area": country.select_one(
            ".country-area"
        ).get_text(strip=True),

        # There are no individual country links on this webpage,
        # so we store the main webpage URL.
        "country_url": url
    })

# Count how many dictionaries (countries) we collected.
len(rows)

250

In [36]:
rows[0]

{'country_name': 'Andorra',
 'capital': 'Andorra la Vella',
 'population': '84000',
 'area': '468.0',
 'country_url': 'https://www.scrapethissite.com/pages/simple/'}

In [37]:
df = pd.DataFrame(rows)
df.head()

,country_name,capital,population,area,country_url
0,Andorra,Andorra la Vella,84000,468.0,https://www.scrapethissite.com/pages/simple/
1,United Arab Emirates,Abu Dhabi,4975593,82880.0,https://www.scrapethissite.com/pages/simple/
2,Afghanistan,Kabul,29121286,647500.0,https://www.scrapethissite.com/pages/simple/
3,Antigua and Barbuda,St. John's,86754,443.0,https://www.scrapethissite.com/pages/simple/
4,Anguilla,The Valley,13254,102.0,https://www.scrapethissite.com/pages/simple/

In [38]:
df.shape

(250, 5)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   country_name  250 non-null    str
 1   capital       250 non-null    str
 2   population    250 non-null    str
 3   area          250 non-null    str
 4   country_url   250 non-null    str
dtypes: str(5)
memory usage: 9.9 KB

In [40]:
df["population"] = (
    df["population"]
    .str.replace(",", "", regex=False)
    .astype(float)
)

df["area"] = (
    df["area"]
    .str.replace(",", "", regex=False)
    .astype(float)
)

df[["country_name", "capital", "population", "area"]].head()

           country_name           capital  population      area
0               Andorra  Andorra la Vella     84000.0     468.0
1  United Arab Emirates         Abu Dhabi   4975593.0   82880.0
2           Afghanistan             Kabul  29121286.0  647500.0
3   Antigua and Barbuda        St. John's     86754.0     443.0
4              Anguilla        The Valley     13254.0     102.0

In [41]:
df.head(5)

,country_name,capital,population,area,country_url
0,Andorra,Andorra la Vella,84000.0,468.0,https://www.scrapethissite.com/pages/simple/
1,United Arab Emirates,Abu Dhabi,4975593.0,82880.0,https://www.scrapethissite.com/pages/simple/
2,Afghanistan,Kabul,29121286.0,647500.0,https://www.scrapethissite.com/pages/simple/
3,Antigua and Barbuda,St. John's,86754.0,443.0,https://www.scrapethissite.com/pages/simple/
4,Anguilla,The Valley,13254.0,102.0,https://www.scrapethissite.com/pages/simple/

In [44]:
df.sort_values("country_name", ascending=False)[[
    "capital",
    "population",
    "area"
]].head(10)

                 capital  population       area
14             Mariehamn     26711.0    1580.00
249               Harare  11651858.0  390580.00
248               Lusaka  13460305.0  752614.00
245                Sanaa  23495361.0  527970.00
65   Laâyoune / El Aaiún    273008.0  266000.00
242             Mata-Utu     16025.0     274.00
240                Hanoi  89571130.0  329560.00
237              Caracas  27223228.0  912050.00
235         Vatican City       921.0       0.44
241            Port Vila    221552.0   12200.00

In [45]:
df["population"].mean().round(2)

np.float64(27445675.58)

In [46]:
df["area"].value_counts().sort_index()

area
0.00           1
0.44           1
1.95           1
6.50           1
10.00          1
              ..
9596960.00     1
9629091.00     1
9984670.00     1
14000000.00    1
17100000.00    1
Name: count, Length: 246, dtype: int64

In [52]:
df[["country_name", "population", "area"]].sort_values(
    "area",
    ascending=False
).head(5)

      country_name    population        area
190         Russia  1.407020e+08  17100000.0
8       Antarctica  0.000000e+00  14000000.0
37          Canada  3.367900e+07   9984670.0
232  United States  3.102329e+08   9629091.0
47           China  1.330044e+09   9596960.0

In [53]:
df[["country_name", "population", "area"]].sort_values(
    "area",
    ascending=True
).head(5)

                    country_name  population   area
231  U.S. Minor Outlying Islands         0.0   0.00
235                 Vatican City       921.0   0.44
137                       Monaco     32965.0   1.95
82                     Gibraltar     27884.0   6.50
219                      Tokelau      1466.0  10.00

In [54]:
df[["country_name", "population", "area"]].sort_values(
    "population",
    ascending=False
).head(5)

      country_name    population       area
47           China  1.330044e+09  9596960.0
104          India  1.173108e+09  3287590.0
232  United States  3.102329e+08  9629091.0
100      Indonesia  2.429683e+08  1919440.0
30          Brazil  2.011033e+08  8511965.0

In [55]:
def data_summary(df):
    print("Rows:", len(df))

    print("\nMissing values:")
    print(df.isna().sum())

    print("\nPopulation range:")
    print(df["population"].min(), "to", df["population"].max())

    print("\nArea range:")
    print(df["area"].min(), "to", df["area"].max())

In [56]:
data_summary(df)

Rows: 250

Missing values:
country_name    0
capital         0
population      0
area            0
country_url     0
dtype: int64

Population range:
0.0 to 1330044000.0

Area range:
0.0 to 17100000.0

In [57]:
books_df = df[[
    "country_name",
    "capital",
    "population",
    "area"
]].copy()

books_df.head()

           country_name           capital  population      area
0               Andorra  Andorra la Vella     84000.0     468.0
1  United Arab Emirates         Abu Dhabi   4975593.0   82880.0
2           Afghanistan             Kabul  29121286.0  647500.0
3   Antigua and Barbuda        St. John's     86754.0     443.0
4              Anguilla        The Valley     13254.0     102.0

In [60]:
import time
import requests
import pandas as pd
from bs4 import BeautifulSoup

# Website URL
page_url = "https://www.scrapethissite.com/pages/simple/"

# Get the webpage
page_response = requests.get(page_url, timeout=30)
page_response.raise_for_status()

# Parse the webpage
page_soup = BeautifulSoup(
    page_response.text,
    "html.parser"
)

# Find all countries
page_countries = page_soup.select("div.country")

# Store the data
all_rows = []

for country in page_countries:

    all_rows.append({
        "country_name": country.select_one(
            ".country-name"
        ).get_text(strip=True),

        "capital": country.select_one(
            ".country-capital"
        ).get_text(strip=True),

        "population": country.select_one(
            ".country-population"
        ).get_text(strip=True),

        "area": country.select_one(
            ".country-area"
        ).get_text(strip=True)
    })

# Create DataFrame
country_df = pd.DataFrame(all_rows)

# Show the size of the dataset
print(country_df.shape)

# Show first 10 rows
country_df.head(10)

(250, 4)

           country_name           capital population       area
0               Andorra  Andorra la Vella      84000      468.0
1  United Arab Emirates         Abu Dhabi    4975593    82880.0
2           Afghanistan             Kabul   29121286   647500.0
3   Antigua and Barbuda        St. John's      86754      443.0
4              Anguilla        The Valley      13254      102.0
5               Albania            Tirana    2986952    28748.0
6               Armenia           Yerevan    2968000    29800.0
7                Angola            Luanda   13068161  1246700.0
8            Antarctica              None          0      1.4E7
9             Argentina      Buenos Aires   41343201  2766890.0